### ISSUE TITLE
cmon do monkeh business

### ISSUE THREAD

**Issue by Alexamakans** [jilleJr/adventofcode-2022-rust#1]
# why?

no monkeh

# how to resolve?

do monkeh

**Comment by Alexamakans** [comment]
very long time to resolve hmm... unsupport!

**Comment by applejag** [comment]
Hi! Thank you for your inquiry. Our team will inspect your ticket as soon as possible.

However please note that there are a lot of vacations during this period, which may cause unexpected delays.

To speak with one of our homo sapiens consultants, press 1.

To keep waiting, press 2.

Thank you for your patience,
Kalle, CMO,
Monkey & Co. Inc. GmbH.

**Comment by Alexamakans** [comment]
2!

recognize import of vacation..!

Good days

**Comment by Alexamakans** [comment]
surely vacation over..

**Comment by applejag** [comment]
hon hon hon,,, stuck with the fingers up the jar of cookie.

surely im a master of procrastination

I've actually had 2 separate vacations since this.

/insert good reason here so he forgives me/

I promise to get this done somewhere around now and later. You have a nugget of my word

**Comment by Alexamakans** [comment]
thamnky For quick respond.

Eager awaiting..!

**Comment by applejag** [comment]
No I can't figure it out. I was unmotivated as it is, and then they hit you with an open task like "find another way to keep your worry levels manageable"

Sorry bruh, I can't do it

**Comment by Alexamakans** [comment]
victory for monkeh.

**Comment by applejag** [comment]
:see_no_evil:
